\c satellite_image_processing;

CREATE SCHEMA IF NOT EXISTS satellite_image_processing;

SET search_path TO satellite_image_processing;

CREATE TABLE IF NOT EXISTS satellite_image_processing.images (
    image_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    width INT NOT NULL,
    height INT NOT NULL,
    filename TEXT NOT NULL UNIQUE,
    image_data BYTEA NOT NULL,
    date_uploaded TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS satellite_image_processing.coordinates (
    coordinates_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id BIGINT REFERENCES images(image_id),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS satellite_image_processing.predictions_roof_type (
    prediction_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    image_id BIGINT REFERENCES images(image_id),
    class_name TEXT NOT NULL,
    time_taken DOUBLE PRECISION NOT NULL,
    confidence FLOAT NOT NULL,
    prediction_type TEXT NOT NULL,
    date_processed TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS satellite_image_processing.detection_solar_panel (
    detection_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    image_id BIGINT REFERENCES images(image_id),
    class_name TEXT,
    confidence FLOAT,
    x FLOAT,
    y FLOAT,
    width FLOAT,
    height FLOAT,
    image_data BYTEA,
    date_processed TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
